# Generated by Django 3.1 on 2020-08-23 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('role', models.TextField(default='sportsman')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
