# Generated by Django 3.1 on 2020-08-24 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('service_id', models.TextField()),
                ('service_secret', models.TextField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
