# Generated by Django 3.1 on 2020-08-25 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AlterField(
            model_name='services',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
