# Generated by Django 3.1 on 2020-08-25 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couples',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('male', models.UUIDField()),
                ('female', models.UUIDField()),
            ],
            options={
                'db_table': 'couples',
            },
        ),
        migrations.CreateModel(
            name='Dancers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('couple_uuid', models.UUIDField(null=True)),
                ('club', models.UUIDField()),
                ('age_group', models.TextField()),
                ('rank', models.CharField(default='E', max_length=1)),
                ('trainer_rank', models.TextField(default='Нет')),
                ('referee_rank', models.TextField(default='Нет')),
            ],
            options={
                'db_table': 'dancers',
            },
        ),
    ]
