# Generated by Django 3.1 on 2020-08-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancers',
            name='club',
            field=models.UUIDField(null=True),
        ),
    ]
