# Generated by Django 3.1 on 2020-08-25 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('app_name', models.TextField()),
                ('app_secret', models.TextField(default='E3EyqmEYw-Dzcg7aTU23XFLAbhJVeg_rzS8K1PL26yk')),
                ('test_scope_1', models.BooleanField(default=False)),
                ('test_scope_2', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
